import Header from './components/Header.jsx'
import './globals.css'
import { Inter } from 'next/font/google'
import './css/Page.css'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Automatas',
  description: 'Generated by Iran Mercado',
}
 const Style = {
  backgroundColor: '#7777'
 }



export default function RootLayout({ children }) {
  return (
    <html style = {Style} lang="en">
      <body className={inter.className}>
        
        <Header/>
          {children}
      </body>
    </html>
  )
}
